### ISSUE TITLE
Kanban Documentation

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/GW-SMHS-BIOC6223#1]
In the [README.md](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/README.md) at:
```
Select Project Template: "Basic kanban" 
```
provide a link to documentation on what a Kanban board is

**Comment by jpat1546** [comment]
https://codeburst.io/an-introduction-to-github-project-boards-2944e6ffbf3c
3c0d2b3dcc7f74ea41a9af649dad8592604bc030
