### ISSUE TITLE
Erin_Bonner_BCO_000531 ready for final review

### ISSUE THREAD

**Issue by ebonner13** [biocompute-objects/GW-SMHS-BIOC6223#106]
Corrections were made and BCO is ready for final review.

**Comment by jpat1546** [comment]
@ebonner13 your BCO has not yet been reviewed. All feedback will be provided for your BCO by Sunday 10/13 11:59pm (#104)

**Comment by jpat1546** [comment]
@ebonner13 your draft BCO has not yet been reviewed. All feedback will be provided for your BCO by Sunday 10/13 11:59pm (#104). Closing this issue and reassigning back to you- once you've made all modifications, you can reopen and reassign this back to me.
