### ISSUE TITLE
Description_domain: check tool version #

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/GW-SMHS-BIOC6223#118]
If you were assigned this issue, the following feedback is relevant for your draft BCO. 

### Feedback
You all had different version #s  Step 1's tool ( Cutadapt) for your group's publication. I would do a quick double-check with the publication. (and feel free to discuss amongst yourselves in the comments below)

https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/bd41089b6cfe4136c4974d21a794c32720252b51/Student_BCOs/Turkey_Alsaeedyhttp___BCO_000520.json#L41

https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/bd41089b6cfe4136c4974d21a794c32720252b51/Student_BCOs/%5BWIP%5DJuntian%20Wei.json#L41

https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/bd41089b6cfe4136c4974d21a794c32720252b51/Student_BCOs/Tomas_Kanholm_BCO_000514.json#L41

---
This issue has been placed as a card in the "To Do" column of your individual projects. Please modify and save your BCO on the [BCO Editor](https://biocomputeobject.org/bco_editor_tst),  with the above feedback provided. Once you've made the modification requested in this issue, move the card to the "Done" column of your projects. Then address the other issues in your "To do" column. 

Once **all** issues assigned to you are addressed (**all** modifications have been made), and your BCO is saved in the BCO editor, please refer to the instructions in #104.

### Additional Resources
- BIOC6223 Lecture 1 BioCompute Introduction 
- [Specification document](https://github.com/biocompute-objects/BCO_Specification)
- [User guide](https://github.com/biocompute-objects/BCO_Specification/blob/master/user_guide.md)

Please make the necessary modifications prior to 10/16.
Comment below if you have any questions. Thank you.

**Comment by jwei2019** [comment]
I will use the latest one and specify it
