### ISSUE TITLE
Extension Domain  - Christian_ZevallosDelgado_BCO_000515

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/GW-SMHS-BIOC6223#138]
If you choose to use this domain, please make sure it is completed. otherwise remove it. 

https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/b8bd696cf1f2efc2bca1d61cf2fcd00f5006d7f8/Student_BCOs/Christian_ZevallosDelgado_BCO_000515.json#L26-L32

**Comment by jpat1546** [comment]
@HadleyKing good catch. I'm not including the extension domain in feedback, as there wasn't enough explanation/time for the students on this domain. Thank you!
