### ISSUE TITLE
Extension Domain -Janisha_Patel_BCO_000010

### ISSUE THREAD

**Issue by HadleyKing** [biocompute-objects/GW-SMHS-BIOC6223#139]
If you choose to use this domain, please make sure it is completed. otherwise remove it.

https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/b8bd696cf1f2efc2bca1d61cf2fcd00f5006d7f8/Student_BCOs/Janisha_Patel_BCO_000010.json#L26-L34

**Comment by jpat1546** [comment]
🦀
