### ISSUE TITLE
Output is in a pdf file 

### ISSUE THREAD

**Issue by zmunoz09** [biocompute-objects/GW-SMHS-BIOC6223#167]
How do I include output if it is pdf?

**Comment by jpat1546** [comment]
@zmunoz09 Is this pdf publically available? If so, you would have the uri to input into your BCO.
Ex: If my output is Git Cheat Sheet, the URI would be: https://education.github.com/git-cheat-sheet-education.pdf

**Comment by zmunoz09** [comment]
Hi,
my pdf does not open up a new window. It directly downloads the document.
So there is not uri to copy from.

**Comment by zmunoz09** [comment]
Hi,
my pdf does not open up a new window. It directly downloads the document.
So there is not uri to copy from.

**Comment by jpat1546** [comment]
@zmunoz09 
Can you provide the webpage that has the link to the pdf here in the comments?

**Comment by zmunoz09** [comment]
SUPPLEMENTARY FIGURES AND TABLES
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4259446/#SD2
Thank you

**Comment by zmunoz09** [comment]
SUPPLEMENTARY FIGURES AND TABLES
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4259446/#SD2
Thank you

**Comment by jpat1546** [comment]
@zmunoz09 On that page, right click "Click here to view," and copy link address. That's your uri.
