### ISSUE TITLE
What should I type in for Checksum of my project, and sha1_checksums on the execution, IO and output domains?

### ISSUE THREAD

**Issue by Albert-Shao** [biocompute-objects/GW-SMHS-BIOC6223#168]
I am not sure what checksum and sha1_checksum are,  and  what  I should type in for Checksum of my project, and various sha1_checksums on the execution, IO and output domains? 

Thanks!

**Comment by jpat1546** [comment]
For this BCO, please use "[yourBCO#]checksum"
For your BCO, it would be: 000542checksum

**Comment by Albert-Shao** [comment]
Thank you!
