### ISSUE TITLE
don't understand what input/outfile domain 

### ISSUE THREAD

**Issue by lhopson15** [biocompute-objects/GW-SMHS-BIOC6223#204]
My publication doesn't state any output files. If they do its' not clear. Input files are SRA data (22 samples). Am I supposed to write out 22 different items?

**Comment by jpat1546** [comment]
@lhopson15 

Your publication does state output files. Please see #167 

If the input files are 22 different samples, they all need to be included in the BCO. The [BCO Example](https://www.biocomputeobject.org//bco_editor_tst/view_example)  that pops up when you first created your BCO shows this.
