### ISSUE TITLE
Feedback - Possible bug

### ISSUE THREAD

**Issue by nikigogate** [biocompute-objects/GW-SMHS-BIOC6223#208]
While modifying my BCO I found a possible bug: 

In the usability domain, if you have some text within " ", then the editor puts in a \ before and after the " ". Please see the screenshots. 
<img width="1290" alt="Screen Shot 2019-10-17 at 1 42 07 PM" src="https://user-images.githubusercontent.com/54719734/67034014-e82d3f80-f0e4-11e9-8fdd-2e1fdf5422af.png">

<img width="1277" alt="Screen Shot 2019-10-17 at 1 42 38 PM" src="https://user-images.githubusercontent.com/54719734/67034024-ed8a8a00-f0e4-11e9-888d-b85a7542d500.png">

If you remove the " " in your text the \  are not inserted into your BCO.

**Comment by kee007ney** [comment]
Resolved in newer version.
