### ISSUE TITLE
How do i log in to the editor? 

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/GW-SMHS-BIOC6223#32]
Help please

**Comment by openbox-bio** [comment]
Is this the biocompute test editor???

-Anjan
=======================================

“Don't be satisfied with stories, how things have gone with others.

Unfold your own myth.”
― Rumi,

========================================

**Comment by jpat1546** [comment]
Sorry @openbox-bio - this was just me showing a student how they would input an issue as a request for help! I should have written test somewhere on it.
