### ISSUE TITLE
midterm: BCO editor_checksum

### ISSUE THREAD

**Issue by jwei2019** [biocompute-objects/GW-SMHS-BIOC6223#34]
I was forced to type the checksum to continue. 
[
![Problem BCO](https://user-images.githubusercontent.com/55710480/66343117-ef03c780-e918-11e9-8cfa-5ec4baf78eb3.JPG)
](url)

**Comment by kee007ney** [comment]
For this BCO, we will use "[yourBCO#]checksum"
