### ISSUE TITLE
midterm: BCO editor_discription domain: input list

### ISSUE THREAD

**Issue by jwei2019** [biocompute-objects/GW-SMHS-BIOC6223#35]
Another issue when writing BCO: what do I put in for input URI? How do I use example.com? And what should the file name be?
![problem BCO 2](https://user-images.githubusercontent.com/55710480/66343540-d5af4b00-e919-11e9-9172-4e4342b6e08f.JPG)

**Comment by kee007ney** [comment]
For the example URI, copy the template format from the example BCO that pops up.
For file type, Google the appropriate file type for the software being used.
