### ISSUE TITLE
BCO editor: checksum and save changes

### ISSUE THREAD

**Issue by jwei2019** [biocompute-objects/GW-SMHS-BIOC6223#36]
This is the issue I talked about early on. The system required me to type in checksum, and I cannot save my file until I type in something for checksum.
![Problem BCO checksum](https://user-images.githubusercontent.com/55710480/66343898-96cdc500-e91a-11e9-9597-edc0fc19e3c1.JPG)

**Comment by kee007ney** [comment]
Duplicate of issue #34
