### ISSUE TITLE
BCO Editor Question (Need Answer ASAP Please)

### ISSUE THREAD

**Issue by nramnarine** [biocompute-objects/GW-SMHS-BIOC6223#69]
What is an extension domain?
What should we put for external data edit points, environment variables for the execution domain?

What is Script in the execution domain?

Is the AB 5500xl Genetic Analyzer a software prerequisite because it's what the authors used for sequencing the CTC genes?

**Comment by kee007ney** [comment]
Extension Domain is a user defined field that can be used to add in anything not already defined (like a specific GitHub repo, which was used in one of the example BCOs).

External data endpoints is an option field to list data access, and environment variables are ways to configure the platform, if necessary. More information about these is in the documentation https://github.com/biocompute-objects/BCO_Specification/blob/master/execution-domain.md (and the BCO Specification link in the instructions has more information about any other domain, too).

Your paper will tell you if they used a specific script to launch or configure the platform. If they did not, then you don't need to list anything here.

No, the gene sequencer is still a wet lab instrument. The bioinformatics portion should start once you've acquired the data. You can put a note about which sequencer was used in your description (the Usability Domain) if you like, but no need to make a pipeline step out of it.
