### ISSUE TITLE
midterm: BCO Editor

### ISSUE THREAD

**Issue by ShyanneG** [biocompute-objects/GW-SMHS-BIOC6223#82]
1-How to fill the "checksum" blank?
I tried: [A-Za-z0-9]+(worked in others editor) but failed.
How could I find the specific one?

2- When I fix the last error warning and click [save changes], it turns to a page shows " invalid version format for BCO". I thought maybe I failed to save it. If it means I would lose what I entered and how can I avoid it next time?

Looking forward to your reply! Thank you so much!

**Comment by kee007ney** [comment]
1 - You'll enter "[yourBCO#]checksum"
It will assign you a number once you've saved it for the first time (something like BCO_000123, you can see it in the URL), so if you've already opened up that field, either collapse it or use a placeholder text to save it the first time (like "placeholder"). Then, when you go back to edit it, you'll be able to put that in there (e.g. "BCO_000123checksum").

2 - Version field has to be filled out. It's a number that you give to it to specify which version of the pipeline you consider it to be (not bco_spec_version, which is 1.3.0 and cannot be changed). It has to be in the format n.n, so you can just go with 1.0.
