### ISSUE TITLE
OncoMX and HIVE (Need answer before Oct 13)

### ISSUE THREAD

**Issue by nbabirye** [biocompute-objects/GW-SMHS-BIOC6223#86]
Hi, is the OncoMX knowledge base integrated within and/or accessible on HIVE? If it is, I am wondering if it can be claimed as an alternative tool/resource to Gene Ontolgy, since it has the cancer genomics data and biomedical ontologies. (GO_BP and GO_CC were used to identify terms related to the classification of gene functions.)

-Group5

**Comment by HadleyKing** [comment]
@nbabirye That is a good question. I can answer, but I think you should try to reach out to the [OncoMX team](https://www.oncomx.org/contact) instead. They will be able to provide you with a more specific answer. I know they are always interested in getting/giving feedback! If you do not get and answer from the contact form (give it a day or so), try reaching out to @hmdinger

**Comment by jpat1546** [comment]
@nbabirye I agree with @HadleyKing . Reassigning this issue back to you while you reach out to the OncoMX team. If you don't hear back from them by EOD Friday, please comment on this issue and reassign this back to me.

**Comment by nbabirye** [comment]
Thank you, I'll reach out to the OncoMX team, and let you know. @jpat1546 and @HadleyKing
