### ISSUE TITLE
Submitted BCO named incorrectly

### ISSUE THREAD

**Issue by jpat1546** [biocompute-objects/GW-SMHS-BIOC6223#93]
**If you were assigned this issue**, an error was found in your work. 

### Error: Your submitted BCO was not named correctly. All [submitted student BCOs](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/tree/master/Student_BCOs) must follow the format outlined on the [README](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/README.md).

This issue has been placed as a card in the "To Do" column of your individual projects. Once complete, placed into "Done" column of your individual project. 

Please make the necessary modifications prior to 10/18. 
Comment below if you have any questions. Thank you.

**Comment by Turkeyalsaeedy** [comment]
I already fixed that thanks!
