### ISSUE TITLE
IMPORTANT- Answer ASAP (thank you!) - Question about my BCO in GitHub Student_BCOs folder

### ISSUE THREAD

**Issue by ECL314** [biocompute-objects/GW-SMHS-BIOC6223#96]
Hi Dr. Keeney and Janisha,
I have a question about my BCO submitted earlier this week.  As this question is an individual issue, yesterday I sent an email with my question, rather than asking my question as an issue here on GitHub.  However, I'm not sure whether my email was received, so I'm submitting an issue on GitHub now.  In my email, I mentioned the following:
"I logged in to the class GitHub page, and I just saw that my BCO, which I uploaded a couple days ago, is indeed located on the class GitHub page but somehow it is located outside of the Student_BCOs folder (screenshot attached).  (I know that the instructions were to upload it to the Student_BCOs folder, and I really thought that I had uploaded it to the Student_BCOs folder a couple days ago (?).) 

Yesterday [Thursday 10/10/2019] I received an email saying that #54 (my pull request) was merged into master.  I am wondering whether I need to upload my BCO again into the Student_BCOs folder and create a new pull request to do so."

I apologize if this is last minute, but could you please let me know whether I need to make a new pull request so that my BCO would be in the Student_BCOs folder?  I know that all of the BCOs in the Student_BCOs folder are being reviewed by 10/13/2019, so I would just like to make sure that my BCO would be reviewed, as it seems to be currently outside of the Student_BCOs folder.  

Thank you,
Elizabeth 

![Screen Shot 2019-10-11 at 3 54 41 PM](https://user-images.githubusercontent.com/56048893/66708982-b7d25380-ed28-11e9-84a4-f9427dde4d49.png)

**Comment by jpat1546** [comment]
@ECL314  Not last minute at all- thank you for submitting this as a Github issue. 
Your BCO has been moved to the correct folder.

**Comment by ECL314** [comment]
Thank you Janisha!  I appreciate it a lot.  I just wanted to make sure that my BCO would be reviewed, as it seemed not to be in the student folder.  
Thanks again

**Comment by jpat1546** [comment]
Of course, no problem! I did notice there was a slight error in your BCO filename. All submitted student BCOs must follow the format outlined in the [README](https://github.com/biocompute-objects/GW-SMHS-BIOC6223/blob/master/README.md). 

An issue (#93) has been placed as a card in the "To Do" column of your individual projects. Once complete, placed into "Done" column of your individual project.

Please make the necessary modifications prior to 10/18.
Comment below if you have any questions. Thanks!

**Comment by ECL314** [comment]
Hi Janisha, thanks about the comment. Yes I changed the file name per the README, and I made a new pull request assigning Dr. Keeney and you.

**Comment by jpat1546** [comment]
Merged #98

**Comment by ECL314** [comment]
Great, thanks Janisha
